import org.apache.commons.io.FileUtils;

import java.net.URL;
import java.net.URLClassLoader;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws ClassNotFoundException {
        System.out.println("------(START)-----");

        System.out.println(new App().getGreeting());

        System.out.println("-----------");

       // Lambada.run();

        ClassLoader cl = ClassLoader.getSystemClassLoader();

        URL[] urls = ((URLClassLoader)cl).getURLs();

        for(URL url: urls){
            System.out.println(url.getFile());
        }


        new FileDemo().go();
        PrintClassLoader.printClassLoaders();
        System.out.println("------(END)-----");

    }
}
